import { LegalLayout, Section, P, Ul, Highlight } from '../components/legal/LegalLayout'

export default function RiskDisclaimerPage() {
  return (
    <LegalLayout
      title="Risk Disclaimer"
      subtitle="Please read this disclaimer carefully before using any tool, scanner, or research output on this platform."
      lastUpdated="May 2026"
      accent="#f59e0b"
    >

      {/* ── Primary notice ─────────────────────────────────────────────── */}
      <Highlight
        color="rgba(245,158,11,0.08)"
        border="rgba(245,158,11,0.28)"
        textColor="#f59e0b"
      >
        ⚠ Stop Hunter Pro is a market research and scanning platform. All tools, scanners,
        scores, grades, alerts, and outputs on this platform are for educational, analytical,
        and research purposes only. Nothing on this platform constitutes financial advice,
        investment advice, or a recommendation to buy, sell, or hold any security or financial
        instrument.
      </Highlight>

      {/* ── 1 ─────────────────────────────────────────────────────────────── */}
      <Section title="1. Nature of the Platform">
        <P>
          Stop Hunter Pro is a multi-scanner trading research platform. Our tools include,
          but are not limited to, the Stop Hunter Pro scanner, SMC Liquidity Scanner,
          Master Screener, Volume Profile Scanner, Options Scanner, and all future scanners,
          dashboards, alerts, scores, grades, and research features.
        </P>
        <P>
          All market research outputs — including scan results, signals, setup classifications,
          confluence scores, grades, order-block detections, and liquidity alerts — are generated
          algorithmically based on predefined technical conditions applied to price and volume data.
          These outputs are informational only.
        </P>
        <P>
          The platform does not consider your personal financial situation, investment objectives,
          risk tolerance, tax position, or time horizon. Our tools are not personalised to you
          individually.
        </P>
        <P>
          <strong style={{ color: '#e1e2ee' }}>
            Stop Hunter Pro is not a SEBI-registered investment adviser, stock broker,
            sub-broker, portfolio manager, or research analyst.
          </strong>{' '}
          Our outputs are not registered investment advice under the SEBI Investment Advisers
          Regulations, 2013, or any other applicable regulation.
        </P>
      </Section>

      {/* ── 2 ─────────────────────────────────────────────────────────────── */}
      <Section title="2. No Guarantee of Profits">
        <Highlight
          color="rgba(255,77,79,0.07)"
          border="rgba(255,77,79,0.22)"
          textColor="#ff6b6b"
        >
          No scanner, score, grade, alert, signal, or setup generated by this platform
          guarantees a profitable trade. Any market research output may be wrong, and acting
          on it may result in financial loss, including loss of your entire invested capital.
        </Highlight>
        <Ul items={[
          'Scanner outputs are based on technical pattern recognition — they do not predict future price movements.',
          'A high score or A-grade setup does not mean a high probability of profit. It reflects confluence of technical conditions only.',
          'Past performance of any pattern, setup type, or scanner strategy does not guarantee future results.',
          'Backtested results, example outputs, and mock scan results are illustrative only and carry no predictive value.',
          'Markets are inherently uncertain. No algorithm, tool, or research platform can consistently predict market direction.',
          'Subscription to a higher-tier plan does not imply better trading results or improved profitability.',
        ]} />
      </Section>

      {/* ── 3 ─────────────────────────────────────────────────────────────── */}
      <Section title="3. Trading and Investing Involve Substantial Risk">
        <P>
          Trading equities, futures, options, and other financial instruments in Indian markets
          (NSE / BSE) involves substantial risk of financial loss, up to and including the loss
          of your entire capital. You should only trade or invest with money you are fully
          prepared to lose.
        </P>
        <Ul items={[
          'Equity markets are subject to market risk, volatility, liquidity risk, and systemic risk.',
          'Futures and options (F&O) carry additional risks: leverage risk, time-decay risk, and expiry-related risk.',
          'Intraday trading and short-term speculation carry higher risk than long-term investing.',
          'Leveraged positions can result in losses exceeding your initial capital.',
          'Illiquid instruments may be difficult or impossible to exit at your intended price.',
          'Stop-loss orders and limit orders do not guarantee execution at the specified price in all market conditions.',
        ]} />
      </Section>

      {/* ── 4 ─────────────────────────────────────────────────────────────── */}
      <Section title="4. Scan Results, Signals, and Scores Are Not Advice">
        <P>
          Every output produced by our scanners — including but not limited to signals,
          setup types, direction labels (bullish/bearish), entry levels, stop-loss levels,
          target levels, confluence scores, grades (A/B/C/D), order-block detections,
          liquidity sweep alerts, and FVG identifications — is a technical observation
          generated by an algorithm.
        </P>
        <P>
          These outputs must not be interpreted as:
        </P>
        <Ul items={[
          'A buy or sell recommendation for any security',
          'A guaranteed profitable signal or edge',
          'Financial advice tailored to your personal situation',
          'An endorsement or advisory opinion on any company or instrument',
          'A solicitation to trade or invest',
          'Portfolio management or investment management services',
        ]} />
        <P>
          You are solely responsible for independently evaluating any scanner output before
          making any trading or investment decision.
        </P>
      </Section>

      {/* ── 5 ─────────────────────────────────────────────────────────────── */}
      <Section title="5. Mock Data and Demonstration Mode">
        <P>
          Certain features of the platform operate in <strong style={{ color: '#e1e2ee' }}>mock mode</strong>,
          which generates entirely simulated, randomly produced data. Mock results are provided
          solely to demonstrate the platform's interface, output structure, and feature set.
        </P>
        <Ul items={[
          'Mock scan results have no connection to real market conditions.',
          'Mock results must not be used as the basis for any real trading or investment decision.',
          'Any feature labelled "mock", "demo", or "simulated" is for illustration purposes only.',
          'When live data mode is introduced, a clear indicator will distinguish live results from mock results.',
        ]} />
      </Section>

      {/* ── 6 ─────────────────────────────────────────────────────────────── */}
      <Section title="6. Market Data Accuracy and Availability">
        <P>
          Market data displayed on or used by the platform — including price data, volume data,
          open interest, and derivatives data — may be subject to the following limitations:
        </P>
        <Ul items={[
          'Data may be delayed relative to real-time market conditions.',
          'Data feeds may contain inaccuracies, gaps, or errors originating from data providers.',
          'Data may be temporarily unavailable due to exchange outages, maintenance windows, or connectivity issues.',
          'Historical data used by scanners may not reflect corporate actions, splits, or delistings in all cases.',
        ]} />
        <P>
          The platform makes no warranty regarding the accuracy, completeness, timeliness,
          or fitness for purpose of any market data or scanner output.
        </P>
      </Section>

      {/* ── 7 ─────────────────────────────────────────────────────────────── */}
      <Section title="7. User Responsibility">
        <P>
          By using the platform and any of its tools, you acknowledge and agree that:
        </P>
        <Ul items={[
          'You are responsible for conducting your own independent research and due diligence before placing any trade.',
          'You treat scanner outputs as one data point among many, not as a standalone signal to act on.',
          'You apply your own position sizing, risk management, and stop-loss discipline to any trade you place.',
          'You consult a qualified, SEBI-registered financial adviser or research analyst for personalised investment guidance.',
          'You are aware of and fully comply with all applicable SEBI regulations, exchange rules, and tax obligations.',
          'You understand that the platform\'s outputs may be incorrect, delayed, or incomplete at any time.',
          'The platform and its developers bear no liability for any financial losses you incur as a result of using scanner outputs.',
        ]} />
      </Section>

      {/* ── 8 ─────────────────────────────────────────────────────────────── */}
      <Section title="8. No Liability for Losses">
        <P>
          To the fullest extent permitted by applicable law, Stop Hunter Pro, its owners,
          developers, employees, and affiliates shall not be liable for any direct, indirect,
          incidental, consequential, special, or punitive damages arising from:
        </P>
        <Ul items={[
          'Your reliance on any scanner output, signal, score, grade, or market research produced by the platform',
          'Trading or investment decisions made using information from the platform',
          'Losses caused by inaccurate, delayed, or unavailable market data',
          'Technical errors, downtime, or interruptions to the platform or its tools',
          'Any other use or misuse of the platform or its features',
        ]} />
      </Section>

      {/* ── 9 ─────────────────────────────────────────────────────────────── */}
      <Section title="9. Regulatory Notice">
        <P>
          Stop Hunter Pro operates as a technology and market research platform. We are not
          registered with SEBI as an investment adviser, research analyst, stock broker,
          sub-broker, depository participant, or portfolio manager.
        </P>
        <P>
          Our platform is designed for self-directed traders and investors who understand the
          risks of the financial markets and who take full responsibility for their own decisions.
          If you are uncertain about any aspect of trading or investing, we strongly recommend
          seeking advice from a SEBI-registered professional before using our tools.
        </P>
        <P>
          Users are solely responsible for ensuring that their use of the platform complies
          with all applicable laws, including SEBI regulations, Income Tax Act provisions,
          and any exchange-specific rules governing their trading activities.
        </P>
      </Section>

      {/* ── 10 ────────────────────────────────────────────────────────────── */}
      <Section title="10. Acceptance of This Disclaimer">
        <P>
          By creating an account, subscribing to any plan, or using any feature of the
          platform, you confirm that you have read, understood, and accepted this Risk
          Disclaimer in full. If you do not accept these terms, please do not use the platform.
        </P>
        <P>
          This disclaimer is subject to change. The most current version will always be
          available at{' '}
          <a href="/risk-disclaimer" style={{ color: '#b3c5ff', textDecoration: 'none' }}>
            stophunterpro.com/risk-disclaimer
          </a>.
          Continued use of the platform following any update constitutes acceptance of the
          revised disclaimer.
        </P>
      </Section>

      {/* ── Contact ────────────────────────────────────────────────────────── */}
      <Section title="Contact">
        <P>
          For questions about this disclaimer, contact us at{' '}
          <a href="mailto:support@stophunterpro.com" style={{ color: '#b3c5ff', textDecoration: 'none' }}>
            support@stophunterpro.com
          </a>{' '}
          or visit our{' '}
          <a href="/support" style={{ color: '#b3c5ff', textDecoration: 'none' }}>
            Support page
          </a>.
        </P>
      </Section>

    </LegalLayout>
  )
}
