"""add nse universe tables

Revision ID: e5de22952863
Revises: fd7589117cee
Create Date: 2026-05-09 15:59:44.047396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5de22952863'
down_revision = 'fd7589117cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nse_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('macro_sector', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('basic_industry', sa.String(length=200), nullable=True),
    sa.Column('yfinance_symbol', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('symbol')
    )
    with op.batch_alter_table('nse_stocks', schema=None) as batch_op:
        batch_op.create_index('ix_nse_stocks_industry', ['industry'], unique=False)
        batch_op.create_index('ix_nse_stocks_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_nse_stocks_sector', ['sector'], unique=False)
        batch_op.create_index('ix_nse_stocks_symbol', ['symbol'], unique=False)

    op.create_table('nse_universes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_nse_universes_slug')
    )
    with op.batch_alter_table('nse_universes', schema=None) as batch_op:
        batch_op.create_index('ix_nse_universes_is_active', ['is_active'], unique=False)

    op.create_table('nse_universe_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('universe_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['nse_stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['nse_universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'stock_id', name='uq_nse_universe_stocks_universe_stock')
    )
    with op.batch_alter_table('nse_universe_stocks', schema=None) as batch_op:
        batch_op.create_index('ix_nse_universe_stocks_stock_id', ['stock_id'], unique=False)
        batch_op.create_index('ix_nse_universe_stocks_universe_id', ['universe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nse_universe_stocks', schema=None) as batch_op:
        batch_op.drop_index('ix_nse_universe_stocks_universe_id')
        batch_op.drop_index('ix_nse_universe_stocks_stock_id')

    op.drop_table('nse_universe_stocks')
    with op.batch_alter_table('nse_universes', schema=None) as batch_op:
        batch_op.drop_index('ix_nse_universes_is_active')

    op.drop_table('nse_universes')
    with op.batch_alter_table('nse_stocks', schema=None) as batch_op:
        batch_op.drop_index('ix_nse_stocks_symbol')
        batch_op.drop_index('ix_nse_stocks_sector')
        batch_op.drop_index('ix_nse_stocks_is_active')
        batch_op.drop_index('ix_nse_stocks_industry')

    op.drop_table('nse_stocks')
    # ### end Alembic commands ###
